// scripts/wrap-css.js
// 把 Tailwind v4 构建出的 CSS 文本包成 ES 模块字符串，供 wrangler（esbuild）
// 打包时作为普通 JS 文本 import —— esbuild 原生不把 .css 当文本导入，
// ?raw 是 Vite 语法 wrangler 不认，故走「CSS 产物 → JS 字符串模块」这条最稳的路。
//
// 输入：src/ui/aperture.generated.css  （tailwindcss -o 产出）
// 输出：src/ui/aperture.generated.js    （export default "<css>"）

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const cssPath = join(root, 'src/ui/aperture.generated.css');
const jsPath  = join(root, 'src/ui/aperture.generated.js');

const css = readFileSync(cssPath, 'utf8');
// JSON.stringify 保证所有特殊字符（引号、换行、反斜杠）合法转义，零歧义。
const js = `// AUTO-GENERATED by scripts/wrap-css.js — do not edit.\n// Tailwind v4 build of src/ui/aperture.css, inlined as a string for the Worker.\nexport default ${JSON.stringify(css)};\n`;
writeFileSync(jsPath, js, 'utf8');
